stages:
- stage: Deploy
  condition: succeeded()
  dependsOn: Build
  #variables: "$[ dependencies.Build.outputs['build.GetAndSetCommitHash.tag'] ]"
  jobs: 
  - template: ../../jobs/applications/deploy.yaml
    parameters: 
      system: ${{ parameters.system }}
      application: ${{ parameters.application }}
      pool_name: ${{ parameters.pool_name }}
      environment_approve: ${{ parameters.environment_approve }}