stages:
- stage: Build
  jobs: 
  - template: ../../jobs/applications/build.yaml
    parameters: 
      system: ${{ parameters.system }}
      application: ${{ parameters.application }}
      pool_name: ${{ parameters.pool_name }}
      environment_approve: ${{ parameters.environment_approve }}
      docker_file_path: ${{ parameters.docker_file_path }}
      