apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-service
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/component: {{ .Values.name }}
    argocd.argoproj.io/instance: {{ .Values.name }}
    backstage.io/kubernetes-id: {{ .Values.name }}
spec:
  selector:
    app: {{ .Values.name }}
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.port }}
      targetPort: {{ .Values.port }}
