# application
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: dynatrace
  description: Description of dynatrace
  #tags:
  #  - DevOps
  links:
    - url: https://argocd.plataformammais-sandbox.n-mercantil.com.br/applications/plataforma-m-mais/dynatrace
      title: Open application
      icon: externalLink
  annotations:
    argocd/project: default
    argocd/app-name: dynatrace
    backstage.io/kubernetes-namespace: plataforma-m-mais
    backstage.io/kubernetes-id: dynatrace
spec:
  type: service
  lifecycle: experimental
  owner: azure_plataformammais_sandbox
  system: observabilidade
