# application
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: grafana
  description: Description of grafana
  #tags:
  #  - DevOps
  links:
    - url: https://argocd.plataformammais-sandbox.n-mercantil.com.br/applications/plataforma-m-mais/grafana
      title: Open application
      icon: externalLink
  annotations:
    argocd/project: default
    argocd/app-name: grafana
    backstage.io/kubernetes-namespace: observabilidade
    backstage.io/kubernetes-id: grafana
spec:
  type: service
  lifecycle: experimental
  owner: azure_plataformammais_sandbox
  system: observabilidade
