apiVersion: v1
kind: Secret
metadata:
  name: frontend-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  POSTGRES_HOST: {{ .Values.postgres.host }}
  POSTGRES_PORT: {{ .Values.postgres.port }}
  POSTGRES_USER: {{ .Values.postgres.user }}
  POSTGRES_PASSWORD: {{ .Values.postgres.password }}
  AZURE_TENANT_ID: {{ .Values.auth.tenantId }}
  MICROSOFT_ENTRAID_CLIENT_ID: {{ .Values.auth.clientId }}
  MICROSOFT_ENTRAID_CLIENT_SECRET: {{ .Values.auth.clientSecret }}
  PERSONAL_ACCESS_TOKEN: {{ .Values.integration.azure.personalAccessToken }}
  SERVICE_ACCOUNT_TOKEN: {{ .Values.kubernetes.serviceAccountToken  }}
