apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/component: frontend
    argocd.argoproj.io/instance: frontend
    backstage.io/kubernetes-id: frontend
spec:
  selector:
    app: frontend
  type: ClusterIP
  ports:
    - name: http
      port: 7007
      targetPort: 7007
