jobs:
- deployment: terraform_apply_deployment
  displayName: 'Terraform_Apply'
  environment: ${{ parameters.environment_approve }}
  pool: $(pool_name)
  condition: succeeded()
  strategy:
    runOnce:
      deploy:
        steps:
        - checkout: self
        - checkout: pipelines
        - template: ../../tasks/tf_apply.yaml
          parameters: 
            terraform_choice: ${{ parameters.terraform_choice }}
            terraform_env: ${{ parameters.terraform_env }}