stages:
- stage: TerraformPlan
  jobs:
  - template: ../../jobs/tf_plan.yaml
    parameters: 
      terraform_choice: ${{ parameters.terraform_choice }}
      terraform_env: ${{ parameters.terraform_env }}