apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.activeGateGroup }}
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  apiToken: {{ .Values.apiToken }}
  dataIngestToken: {{ .Values.dataIngestToken }}
