apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name }}
  description: ${{ values.description }}
  annotations:
    argocd/project: default
    argocd/app-name: ${{ values.name }}
    backstage.io/kubernetes-namespace: ${{ values.system }}
    backstage.io/kubernetes-id: ${{ values.name }}
spec:
  type: service
  lifecycle: experimental
  owner: azure_plataformammais_sandbox
  system: ${{ values.system }}
