trigger:
  - main

name: $(Date:yyyyMMdd)$(Rev:.r)

resources:
  repositories:
    - repository: app-of-apps
      type: git
      name: MB/_git/MB.DVX.AppOfApps.PlataformaM_Mais
      ref: 'refs/heads/main'
    - repository: pipelines
      type: git
      name: MB/_git/MB.DVX.CICD.Pipelines.Templates
      ref: 'refs/heads/main'
extends:
  template: resources/pipeline-app-template.yaml@pipelines
  parameters: 
    system: ${{ values.system }}
    application: ${{ values.name }}
    pool_name: agent-dvx-gke
    environment_approve: terraform-iac-test
    docker_file_path: '$(Build.SourcesDirectory)/$(Build.Repository.Name)/Dockerfile'