name: ${{ values.name }}
namespace: ${{ values.system }}
replicaCount: 2

image:
  repository: imagensmbprd.azurecr.io/mb.dvx.plataformam_mais.template-dotnet8
  tag: 192893
  pullPolicy: IfNotPresent

imagePullSecrets:
  name: docker-credentials

port: 8080

resources:
  requests:
    memory: "128Mi"
    cpu: "100m"
  limits:
    memory: "256Mi"
    cpu: "200m"

ingress:
  host: ${{ values.name }}.plataformammais-sandbox.n-mercantil.com.br
  gateway: istio-system/istio-ingressgateway