apiVersion: v1
kind: Namespace
metadata:
  name: plataforma-m-mais
  labels:
    istio-injection: enabled

---

apiVersion: v1
kind: Namespace
metadata:
  name: observabilidade
  labels:
    istio-injection: enabled
---

apiVersion: v1
kind: Namespace
metadata:
  name: dynatrace
  labels:
    istio-injection: enabled
