jobs:
- job: build
  displayName: Running Build to ${{parameters.application}}  
  pool: ${{ parameters.pool_name }}
  steps:
  - checkout: self
  - checkout: pipelines
  - template: ../../tasks/applications/docker.yaml
    parameters: 
      system: ${{ parameters.system }}
      application: ${{ parameters.application }}
      docker_file_path: ${{ parameters.docker_file_path }}
