jobs:
- deployment: deploy
  displayName: 'Deploy'
  environment: ${{ parameters.environment_approve }}
  pool: ${{ parameters.pool_name }}
  condition: succeeded()
  strategy:
    runOnce:
      deploy:
        steps:
        - checkout: self
        - checkout: pipelines
        - checkout: app-of-apps
        - template: ../../tasks/applications/publish-argocd.yaml
          parameters: 
            system: ${{ parameters.system }}
            application: ${{ parameters.application }}