apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.namespace }}
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  apiToken: {{ .Values.apiToken | b64enc }}
  dataIngestToken: {{ .Values.dataIngestToken | b64enc }}
