apiVersion: v1
kind: ConfigMap
metadata:
  name: ip-masq-agent
  namespace: kube-system
data:
  config: |
    nonMasqueradeCIDRs: 
    - 10.192.72.0/24
    masqLinkLocal: false
    resyncInterval: 60s