---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  generation: 1
  labels:
    app: ${APPNAME}
  name: ${APPNAME}
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${APPNAME}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ${APPNAME}
    spec:
      containers:
      - image: ${CONTAINER_REGISTRY}/${APPNAME}:${BUILDID}
        imagePullPolicy: Always
        name: ${APPNAME}
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
        command: [ "/app/mtr-exporter" ]
        args: [ "-bind",":80", "--", "-c", "2", "-n", "${ENDPOINT}", "--tcp", "--port=9092" ]
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      imagePullSecrets:
      - name: docker-credentials
      tolerations:
      - key: "purpose"
        operator: "Equal"
        value: "infra"
        effect: "NoExecute"

---
apiVersion: v1
kind: Service
metadata:
  name: ${APPNAME}
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    name: ${APPNAME}
  selector:
    app: ${APPNAME}
