steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      cd ${{ parameters.system }}
      REVISION=$(echo "$(Build.SourceVersion)" | cut -c1-5)
      echo "Revision: $REVISION"
      echo "##vso[task.setvariable variable=tag;;isOutput=true]$REVISION"
  name: GetAndSetCommitHash
  displayName: 'Get commit hash and set tag'
  