steps:
- task: Docker@2
  displayName: 'Login no Docker Registry'
  inputs:
    command: login
    containerRegistry: DockerRegistryMB
- task: Docker@2
  displayName: 'Docker build'
  inputs:
    containerRegistry: DockerRegistryMB
    repository: '$(Build.Repository.Name)'
    command: build
    tag: $(Build.BuildId)
    Dockerfile: ${{ parameters.docker_file_path }}
    arguments: '--build-arg http_proxy=$(PROXY_HTTP) --build-arg https_proxy=$(PROXY_HTTPS) --progress=plain'
- task: Docker@2
  displayName: 'Docker push'
  inputs:
    containerRegistry: DockerRegistryMB
    repository: '$(Build.Repository.Name)'
    command: push
    tags: |
      $(Build.BuildId)
