steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      lowercase_name=$(echo "$(Build.Repository.Name)" | tr '[:upper:]' '[:lower:]')
      echo "##vso[task.setvariable variable=lowercaseRepositoryName]$lowercase_name"
  displayName: 'Convert Build.Repository.Name to lowercase in Bash'
- script: |
      echo "Lista diretorios: `ls -l MB.DVX.AppOfApps.PlataformaM_Mais`"
      git -C ./MB.DVX.AppOfApps.PlataformaM_Mais config user.name
      git -C ./MB.DVX.AppOfApps.PlataformaM_Mais config user.email
      git -C ./MB.DVX.AppOfApps.PlataformaM_Mais fetch
      git -C ./MB.DVX.AppOfApps.PlataformaM_Mais status
      git -C ./MB.DVX.AppOfApps.PlataformaM_Mais checkout main
      git -C ./MB.DVX.AppOfApps.PlataformaM_Mais pull
      git -C ./MB.DVX.AppOfApps.PlataformaM_Mais config user.email "pipeline-plataforma-m-mais@mercantil.com.br"
      git -C ./MB.DVX.AppOfApps.PlataformaM_Mais config user.name "Plataforma M Mais"
      git -C ./MB.DVX.AppOfApps.PlataformaM_Mais config credential.helper '!f() { sleep 1; echo "username=${GITUSERNAME:-pat}"; echo "password=$GITPASSWORD"; }; f'
      git -C ./MB.DVX.AppOfApps.PlataformaM_Mais remote set-url origin https://$GITUSERNAME@devops.mercantil.com.br/Tecnologia_MB/MB/_git/MB.DVX.AppOfApps.PlataformaM_Mais
      echo "Show repo:"
      echo "$(lowercaseRepositoryName)"
      echo "Show tag:"
      echo "$(Build.BuildId)"
      echo "Executando Sed"
      sed -i 's|repository: .*|repository: imagensmbprd.azurecr.io/$(lowercaseRepositoryName)|' ./MB.DVX.AppOfApps.PlataformaM_Mais/sistemas/${{ parameters.system}}/manifestos/${{ parameters.application}}/values-sandbox.yaml
      sed -i 's|tag: .*|tag: $(Build.BuildId)|' ./MB.DVX.AppOfApps.PlataformaM_Mais/sistemas/${{ parameters.system}}/manifestos/${{ parameters.application}}/values-sandbox.yaml
      echo "Add file"
      git -C ./MB.DVX.AppOfApps.PlataformaM_Mais add .
      echo "Executando commit"
      export GIT_TERMINAL_PROMPT=1
      git -C ./MB.DVX.AppOfApps.PlataformaM_Mais commit -m "${{ parameters.application}}: update image to version $(Build.BuildId)"
      git -C ./MB.DVX.AppOfApps.PlataformaM_Mais status
      git -C ./MB.DVX.AppOfApps.PlataformaM_Mais push
  displayName: 'Commit and push updated manifest to GitOps repo'
  env:
    GITUSERNAME: $(DEVOPS-Usuario)
    GITPASSWORD: $(DEVOPS-Senha) 