apiVersion: apps/v1
kind: Deployment
metadata:
  name: azdevops-deployment
  namespace: azure-devops-agents
  labels:
    app: azure-agent-gke-dev
spec:
  replicas: 2 # Configuration to always keep one agent running
  selector:
    matchLabels:
      app: azure-agent-gke-dev
  template:
    metadata:
      labels:
        app: azure-agent-gke-dev
    spec:
      containers:
      - name: kubepodcreation
        image: imagensmbprd.azurecr.io/agent:129813
        env:
          - name: AZP_URL
            valueFrom:
              secretKeyRef:
                name: azdevops
                key: AZP_URL
          - name: AZP_TOKEN
            valueFrom:
              secretKeyRef:
                name: azdevops
                key: AZP_TOKEN
          - name: AZP_POOL
            valueFrom:
              secretKeyRef:
                name: azdevops
                key: AZP_POOL
        volumeMounts:
        - mountPath: /var/run/docker.sock
          name: docker-volume
      volumes:
      - name: docker-volume
        hostPath:
          path: /var/run/docker.sock
        tolerations:
      - key: "purpose"
        operator: "Equal"
        value: "infra"
        effect: "NoExecute"
      imagePullSecrets:
      - name: docker-credentials