apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dynatrace-operator
  namespace: plataforma-m-mais
spec:
  project: default
  source:
    repoURL: oci://public.ecr.aws/dynatrace/dynatrace-operator
    targetRevision: "latest"
    chart: dynatrace-operator
  destination:
    server: https://kubernetes.default.svc
    namespace: observabilidade
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dynatrace
  namespace: plataforma-m-mais
spec:
  project: default
  source:
    repoURL: https://devops.mercantil.com.br/Tecnologia_MB/MB/_git/MB.DVX.AppOfApps.PlataformaM_Mais
    path: sistemas/observabilidade/manifestos/dynatrace
    targetRevision: HEAD
    helm:
      valueFiles:
        - values-sandbox.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: observabilidade
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
