apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dynatrace
  namespace: plataforma-m-mais
spec:
  project: default
  sources:
    - repoURL: https://devops.mercantil.com.br/Tecnologia_MB/MB/_git/MB.DVX.AppOfApps.PlataformaM_Mais
      targetRevision: HEAD
      path: sistemas/observabilidade/manifestos/operator
      directory:
        recurse: false
    - repoURL: https://devops.mercantil.com.br/Tecnologia_MB/MB/_git/MB.DVX.AppOfApps.PlataformaM_Mais
      path: sistemas/observabilidade/manifestos/dynatrace
      targetRevision: HEAD
      helm:
        valueFiles:
          - values-sandbox.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: observabilidade
  syncPolicy:
    automated:
      prune: true
      selfHeal: true