apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: plataforma-m-mais
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: grafana
    targetRevision: 11.3.24  # Versão específica do Grafana Helm chart
    helm:
      values: |
        admin:
          user: "admin"
          password: "admin123"
        grafana:
          enabled: true
          ingress:
            enabled: true
            hosts:
              - grafana.plataformammais-sandbox.n-mercantil.com.br
            gateway: istio-system/istio-ingressgateway
          persistence:
            enabled: true
            size: 10Gi  # Ajuste o volume de acordo com as necessidades do seu ambiente
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "200m"
          nodeSelector:
            layer: apps
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                      - key: layer
                        operator: In
                        values:
                          - apps
  destination:
    server: https://kubernetes.default.svc
    namespace: observabilidade
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: grafana-virtualservice
  namespace: observabilidade
spec:
  hosts:
    - "grafana.plataformammais-sandbox.n-mercantil.com.br"
  gateways:
    - istio-system/istio-ingressgateway
  http:
    - match:
        - uri:
            prefix: "/"
      route:
        - destination:
            host: grafana
            port:
              number: 3000
