parameters:
- name: system
  type: string
  default: null
- name: application
  type: string
  default: null
- name: pool_name
  type: string
  default: null
- name: environment_approve
  type: string
  default: null
- name: docker_file_path
  type: string
  default: null

trigger:
- main

variables:
- template: ../variables/variables-azurePipelines.yaml
- group: Deploy DevOps
- group: Teste-DevEx

stages:
- template: ../stages/applications/stage-build.yaml@pipelines
  parameters: 
    system: ${{ parameters.system}}
    application: ${{ parameters.application }}
    pool_name: ${{ parameters.pool_name }}
    environment_approve: ${{ parameters.environment_approve }}
    docker_file_path: ${{ parameters.docker_file_path }}
- template: ../stages/applications/stage-deploy.yaml@pipelines
  parameters: 
    system: ${{ parameters.system}}
    application: ${{ parameters.application }}
    pool_name: ${{ parameters.pool_name }}
    environment_approve: ${{ parameters.environment_approve }}
